openapi: 3.0.0
info:
  title: Your API Documentation
  version: 1.0.0
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: User registered successfully
        400:
          description: Bad request. Invalid input or missing fields
        500:
          description: Internal server error
  /api/auth/signin:
    post:
      summary: Sign in to the application
      description: Sign in to the application with a username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful authentication
        401:
          description: Unauthorized - Invalid password or account not verified
        404:
          description: User not found
        500:
          description: Internal Server Error
  /api/auth/signout:
    post:
      summary: Sign out from the application
      description: Sign out from the application by clearing the authentication token cookie
      responses:
        200:
          description: Successfully signed out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        500:
          description: An error occurred while signing out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/auth/verifemail:
    get:
      summary: Verify user's email
      description: Verify a user's email using a verification token
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: The verification token received via email
      responses:
        200:
          description: Email successfully verified
        401:
          description: Unauthorized - Invalid token or token expired
        404:
          description: User not found
  /api/auth/forget-password:
    post:
      summary: Send password reset instructions to the user's email
      description: Send password reset instructions to the user's email using their registered email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        200:
          description: Password reset instructions sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message
        404:
          description: User not found with the provided email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A user not found message
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: An internal server error message
  /api/auth/reset-password:
    post:
      summary: Reset user password
      description: Reset a user's password using a token and a new password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        200:
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Mot de passe réinitialisé avec succès
        400:
          description: Invalid or expired reset link
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Lien de réinitialisation invalide ou expiré
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
